apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: whoami
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: laurin.notemann@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - http01:
        ingress:
          class: traefik
