apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: whoami
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: laurin.notemann@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
    - http01:
        ingress:
          class: traefik
